### ISSUE TITLE
After a study completes, the controls are not accessible

### ISSUE THREAD

**Issue by devilgate** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#29]
If you look at the attached image, you'll see that the green information bars cover the controls at the top of the page, and that they don't have 'X's to close them. Seems that the only way to do anything else is to refresh, which logs you out...

I don't think it was like this a few days ago. I think the close controls on the bars have disappeared. 

And it seems to be only in Safari, as I've just tried in Chrome and the 'X's are there. But as I say, they were there a few days ago in Safari.

![screen shot 2018-05-03 at 15 52 31](https://user-images.githubusercontent.com/4842280/39585680-43ddcbc4-4eed-11e8-925c-b04924916967.png)

**Comment by peterhambly** [comment]
Looks like a Safari bug I am afraid. There isn't a newer version of the library  ng-notifications-bar - v0.0.16. Can you try http://beletsky.net/ng-notifications-bar/ and see if the test program works.

**Comment by devilgate** [comment]
Today this has fixed itself: the close controls are back. I don't know what was going on yesterday.
