### ISSUE TITLE
On-screen toggle between disease mapping and risk analysis doesn't work properly

### ISSUE THREAD

**Issue by devilgate** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#52]
Something is not right in the front end regarding the RA/DM toggle. I frequently try to submit a risk analysis and the generated JSON contains a `disease_mapping` block. Sometimes the opposite happens: what I submit as a disease mapping study contains a `risk_analysis` block. 

Sometimes I can prevent this by judicious toggling back and forth of the switch, logging off and on, forced reloading, and so on. But not always. The only way I've found to guarantee it being right is to stop and start Tomcat.

The following steps will guarantee a failure. From a freshly-started Tomcat:

1. Log on and submit a simple disease-mapping study. Let it run to completion.
2. Load a saved risk-analysis study from file, and run it.

In the risk analysis development branch (`issue/#51_integrate_risk_analysis_script`) it will fail in `Adj_Cov_Smooth_JRI.R`, which should not even be called for a risk analysis. In the current `master` something similar happens. Sometimes you can't even submit the study, because the JSON is wrong. The error message in those cases is: 'Error: Record "Disease mapping study" field "Name" cannot be empty.'

On the other hand, I have now tried loading the `Test Risk Analysis.json` file in `Testing/Study Tests`, and it ran successfully through -- as a disease-mapping study, as far as I can tell.

**Comment by devilgate** [comment]
As of today, switching from disease mapping to risk analysis works, but not the reverse.

**Comment by peterhambly** [comment]
Created specific branch: [Issue-%2352-RA-DM-switching](https://github.com/smallAreaHealthStatisticsUnit/rapidInquiryFacility/tree/Issue-%2352-RA-DM-switching)

**Comment by peterhambly** [comment]
Added verification of *SubmissionStateSerice*, *ModelService* and diagnostics. Bug traced to initialiser in *ModelService*. Added error messages for missing callbacks in services (*SelectStateService* in particular).

*SubmissionStateSerice* is incorrectly initialised when viewing maps. This causes verification to fail.

**Comment by peterhambly** [comment]
Fix for incorrect use of submission state numerator string (as object)  …
This was causing the numerator table not to be displayed properly when returning from the data viewer/mapper

**Comment by peterhambly** [comment]
Fixed by pull request #70
