### ISSUE TITLE
Sort (ex disease) map info boxes - merge into 1 box, add support for homogeneity, exposure covariates in risk analysis

### ISSUE THREAD

**Issue by peterhambly** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#65]
Sort (ex disease) map info boxes - merge into 1 box, add support for homogeneity, exposure covariates in risk analysis

**Comment by peterhambly** [comment]
To this can be added geography support as the twin maps must be the same geography.

**Comment by bparkes** [comment]
In older versions of the RIF, the exposure for geographical areas was defined using 'exposure covariates' - reusing the covariate table to store the exposure. This would probably still work, but only when multiple covariates can be defined. It seems sensible to combine the task of implementing area-level exposure with adding support for multiple covariates.

**Comment by peterhambly** [comment]
This is fixed by pull #135 for issue #127 Risk Analysis specific D3 graphs
