### ISSUE TITLE
Using the  Heathrow and/or Incinerators studies to test the RIF

### ISSUE THREAD

**Issue by peterhambly** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#74]
# Work required to run postcode level studies

* Postcode geography preparation: 1 week;
* Performance issues caused by 1.7 million shapes (8x COA) in the front end and the database extract may need to be solved: 0-2 weeks;
* New functionality: 2 weeks
  * Risk analysis only - must be aggregated; new functionality to limit a geography to risk analysis;
  * The identifiability of risk analysis post-coded bands needs to be considered (i.e. a minimum number of postcodes in a band);
  * Extract and study/comparison area tables will *NOT* postcodes (i.e. the *area_id* field will be null). This may impact on the R scripts and the logistic regression;
  * New functionality to hash postcodes to database codings in extract (geolevel will hold postcodes);

# Issues with Heathrow or Incinerators re-runs

* No multiple external covariate support. Adding it would take about 2-3 months (needs to be estimated properly but involves substantial change to all layers; with potentially the need to change the extract code and the structure of the results tables). The old RIF did not have multiple external covariate support so the functionality and math will need to be clearly defined. It should be possible to add additional  "unused" covariates to the extract as a work around taking less time (3-6 weeks). The work around should be far simpler as it should not need to touch the R code, map display or the export outputs (apart from the CSV of the extract table);
* Assumes  that the 2011 census geography is used. Use of 2001 geography will add 2 weeks to timescales;
* Add support for additional statistical options:
  * Logistic regression (generalised liner model) implies multiple covariates are needed;
  * Poisson regression;

These are best added as extensions to the RIF so it can be made extensible, however this would take longer than just adding them as new functionality. Adding a new option (there are two) it would take about 2-4 weeks (needs to be estimated properly but involves change to all layers). Needs statistician time.

Do we really need to add this to the RIF; would it not be better done as an R script running on the extract? It could then be documented as a worked example.

* Data preparation and loading will need to be done by the database team. The RIF team can install Postgres and the RIF (assuming walled garden can be accessed from the VPN), provide example load scripts and assist with loading the data.
  
# Timescales

* Adding postcode level support: 5 weeks;
* Server preparation and data loading: 1-2 weeks;
* Testing and resolutions of problems: 2-3 weeks;
* Running of studies and interpretation of results: 1-2 weeks;

That will allow for the running of a basic study. Other "options":

* Multiple external covariate support: 2-3 months. A work around adding additional "unused" covariates to the extract: 3-6 weeks;
* ICD 9 support: 4 weeks;
* Use of 2001 geography: 2 weeks;
* Additional statistical methods:
  * RIF Poisson regression: 2-4 weeks;
  * RIF Logistic regression (implies multiple covariates): 2-4 weeks;
or:
  * R script on CSV extract Poisson regression: 1 week;
  * R script on CSV extract Logistic regression (implies multiple covariates): 1 week;
	
# Risks

In order of impact, highest first:

* Issues in the front end with high resolution administrative geographies (MSOA2011/ward and higher). It is believed that the performance issues are caused by the mouse event triggers as Leaflet need to work out which shape the mouse click is within. With 220,000 shapes this causes problems. The work around is to disable the events at these resolutions. If this does not work acceptably then conventional image tiles will need to be used. This will require substantial work. A long term solution is discussed in issue #66;
* Bugs in RIF extract or R code giving the wrong results. Disease mapping has been tested with another tool (???) and SAHSULAND data and found to be the same aside from differences in the BYM implementation;
* Performance issues in the extract. SQL was tested on Oracle with study area only for all 20 Health Atlas outcomes in one multi investigation  extract in 4 minutes. Postgres and SQL server required the same slight restructure in the code to run efficiently but may require the code to be broken down into three component parts. Based on experience processing geography this is more likely to happen to SQL Server which is not the target database. It is assumed that Postgres partitioning will be used for good performance; the native Postgres 10 implementation has not been  tested. The RIF currently uses partitioning on the geospatial table using the Postgres 9 method;
* Work around adding additional "unused" covariates to the extract may need the R code to be modified so it ignores them (I am assuming the code aggregates so is not an issue);

# Conclusions
  
I would re-run Heathrow first as a series of 2011 geography risk analysis studies at OA and COA level each with a different single external covariate, e.g. ethnicity, deprivation (which I think was derived from Lung Cancer incidence). The work around adding additional "unused" covariates to the extract would be added  and then run the Poison regression used by the Heathrow study as R code on the CSV extract. 
I assume all the covariates are required for the Poisson regression to work.

The team would then move on add postcode level support; This would then allow the Incinerators study to be re-run again as a risk analysis with additional "unused" covariates and the Logistic regression run on the extract.

This will create a set of staged deliverables which can then be managed appropriately

**Comment by devilgate** [comment]
I think we can consider this done now.
